# Pandas is a python library that allows us to load, clean and analyze table structured data.

In [1]:
import numpy as np
import pandas as pd

# Series & DataFrame Basics

In [2]:
# series (1D, labeled)
S1 = pd.Series([65, 12, 90],index = ["a", "b", "c"])
print(S1["c"])
print(S1.values)
print(S1.index)

90
[65 12 90]
Index(['a', 'b', 'c'], dtype='str')

In [16]:
# DataFramea (2D Table)
df1 = pd.DataFrame({"City":["Chennai", "Bomaby","Bengaluru","Pune"],
                    "Name":["Thomas", "Andrew","William","Josh"],
                    "Age":[24,31,29,23]}, index = [1,2,3,4]) #making DataFrames from dictionary
print(df1)

        City     Name  Age
1    Chennai   Thomas   24
2     Bomaby   Andrew   31
3  Bengaluru  William   29
4       Pune     Josh   23

In [19]:
# surveying the data
df1.head() #by default first 5 rows if nothing given
df1.tail(2) #by default last 5 rows if nothing given
df1.shape #gives dimensions of DataFrame (rows, columns)
df1.columns #gives column names
df1.index #returns row labels
df1.dtypes #gives datatype of each column

City      str
Name      str
Age     int64
dtype: object

In [23]:
# to summarize a DataFrame
df1.info() #gives information of each column.
df1.describe() #gives statistical details of DataFrame
df1.describe(include = "object") #for text columns

<class 'pandas.DataFrame'>
Index: 4 entries, 1 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   City    4 non-null      str
 1   Name    4 non-null      str
 2   Age     4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 128.0 bytes

C:\Users\Rayan chakraborty\AppData\Local\Temp\ipykernel_34180\2838960585.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df1.describe(include = "object") #for text columns

           City    Name
count         4       4
unique        4       4
top     Chennai  Thomas
freq          1       1

In [27]:
# one column of a DataFrame is a Series
df1["Age"]
type(df1["Age"]) # returns Pandas Series Datatype
df1["Age"].mean()

np.float64(26.75)

In [29]:
# connection with numpy
df1["Age"].to_numpy() #this series is converted to an numpy array now
pd.DataFrame(np.arange(12).reshape(3,4)) #here numpy array is converted to DataFrame

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

# Data Loading

In [6]:
df = pd.DataFrame({
    "name":  ["Amit", "Riya", "Kabir", "Sara", "Neha"],
    "age":   [21, 22, 20, 23, 22],
    "city":  ["Delhi", "Pune", "Delhi", "Agra", "Pune"],
    "marks": [78.5, 88.0, 65.0, 92.5, 71.0]
})
print(df)

#if we want to save this dataframe in different formats like csv, excel or something else
df.to_csv(r"C:\Users\Rayan chakraborty\Downloads\students.csv", index=False) # give the proper path and index = False is to remove extra index column

    name  age   city  marks
0   Amit   21  Delhi   78.5
1   Riya   22   Pune   88.0
2  Kabir   20  Delhi   65.0
3   Sara   23   Agra   92.5
4   Neha   22   Pune   71.0

In [8]:
df.to_excel(r"C:\Users\Rayan chakraborty\Downloads\student1.xlsx", index=False) #excel version

In [9]:
df.to_json(r"C:\Users\Rayan chakraborty\Downloads\student2.json", index=False) #json version

In [ ]:
# to read particular csv files
pd.read_csv(r"C:\Users\Rayan chakraborty\Downloads\students.csv", usecols=["name", "marks"])    # only these columns
pd.read_csv(r"C:\Users\Rayan chakraborty\Downloads\students.csv", nrows=3)                      # only first 3 rows
pd.read_csv(r"C:\Users\Rayan chakraborty\Downloads\students.csv", index_col="name")             # making name as index
pd.read_csv(r"C:\Users\Rayan chakraborty\Downloads\students.csv", dtype={"age": "float"})       # setting datatype

# Selecting Data

In [6]:
df = pd.DataFrame({
    "name":["Ram", "Prem", "Ujjwal", "Praful"],
    "age":[26, 30, 29, 25],
    "City":["Chennai", "Mumbai", "Delhi", "Bengaluru"]
})
df

     name  age       City
0     Ram   26    Chennai
1    Prem   30     Mumbai
2  Ujjwal   29      Delhi
3  Praful   25  Bengaluru

In [5]:
#selecting columns
print(df["age"])
print(df[["name","age"]])

0    26
1    30
2    29
3    25
Name: age, dtype: int64
     name  age
0     Ram   26
1    Prem   30
2  Ujjwal   29
3  Praful   25

In [10]:
# using iloc (here end is excluded) and here we use position
df.iloc[0] #row of index zero
df.iloc[0:2] #row of index 0 and 1 here 2 is excluded
df.iloc[:,0:2] # all rows and columns of index 0 and 1 (2 excluded)
df.iloc[[0,2],[0,1]] # row of index 0 and 2, column of index 0 and 1

     name  age
0     Ram   26
2  Ujjwal   29

In [16]:
# using loc (here end is also included) and here we can use labels only for columns
df.loc[0]
df.loc[0:2]
df.loc[0:2, "name":"age"]
df.loc[[0,3],["name","City"]]

     name       City
0     Ram    Chennai
3  Praful  Bengaluru

In [19]:
df1 = pd.DataFrame({
    "name":  ["Amit", "Riya", "Kabir", "Sara", "Neha"],
    "age":   [21, 22, 20, 23, 22],
    "city":  ["Delhi", "Pune", "Delhi", "Agra", "Pune"],
    "marks": [78.5, 88.0, 65.0, 92.5, 71.0]
})

In [22]:
# Filtering (boolean masking, just like NumPy)
df1[df1["marks"] > 75]
df1[df1["city"] == "Delhi"]
df1[(df1["age"] >= 22) & (df1["marks"] > 70)]

   name  age  city  marks
1  Riya   22  Pune   88.0
3  Sara   23  Agra   92.5
4  Neha   22  Pune   71.0

In [29]:
# isin, between, string matchings
df1[df1["city"].isin(["Delhi","Agra"])]
df1[df1["marks"].between(60,75)]
df1[df1["name"].str.contains('a')]
df1[df1["name"].str.startswith('S')]

   name  age  city  marks
3  Sara   23  Agra   92.5

In [33]:
# Filter + column together
df1.loc[df1["marks"]>70,["name","marks"]]

   name  marks
0  Amit   78.5
1  Riya   88.0
3  Sara   92.5
4  Neha   71.0

In [35]:
# changing the index
df2 = df1.set_index("name")
df2.loc["Riya"]
df2.loc["Neha", "age"]
df2.loc["Kabir", ["city","marks"]]
df2.reset_index() #shows the older indexed

       age   city  marks
name
Amit    21  Delhi   78.5
Riya    22   Pune   88.0
Kabir   20  Delhi   65.0
Sara    23   Agra   92.5
Neha    22   Pune   71.0

In [42]:
# to modify values
df1.loc[df1["marks"] < 70, "marks"] = 70